/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

// Game
export const NEW_GAME_REQUEST = 'NEW_GAME_REQUEST';
export const NEW_GAME_REQUEST_SUCCESS = 'NEW_GAME_REQUEST_SUCCESS';
export const NEW_GAME_REQUEST_FAIL = 'NEW_GAME_REQUEST_FAIL';

export const VERIFY_GAME_REQUEST = 'VERIFY_GAME_REQUEST';
export const VERIFY_GAME_REQUEST_SUCCESS = 'VERIFY_GAME_REQUEST_SUCCESS';
export const VERIFY_GAME_REQUEST_FAIL = 'VERIFY_GAME_REQUEST_FAIL';

export const THROW_REQUEST = 'THROW_REQUEST';
export const THROW_REQUEST_SUCCESS = 'THROW_REQUEST_SUCCESS';
export const THROW_REQUEST_FAIL = 'THROW_REQUEST_FAIL';

export const ADD_GAME_MESSAGE = 'ADD_GAME_MESSAGE';

// Message
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
